version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: passbook-vault-db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
    ports:
      - "5432:5432"
  
  app:
    build: .
    container_name: passbook-vault-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
