spring.datasource.url=jdbc:postgresql://postgres:5432/passbook_vault
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

file.upload-dir=/app/uploads